[package]
name = "gnuplot"
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.3"
anyhow = "1.0.89"
nadi_core = {version = "0.4.0", path = "../../nadi_core"}
