[package]
name = "gnuplot"
version = "0.4.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.3"
nadi_core = {version = "0.7.0", path = "../../nadi-system/nadi_core"}
