[package]
name = "calc_errors"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
abi_stable = "0.11.3"
nadi_core = {version = "0.6.0", path="../../nadi_core"}
