[package]
name = "html"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nadi_core = {version = "0.7.0", path = "../../nadi-system/nadi_core"}
abi_stable = "0.11.3"
anyhow = "1.0.93"

